// Currency utility functions

// Format amount with currency symbol
export const formatCurrency = (amount, currency = { code: 'USD', symbol: '$' }) => {
  if (amount === null || amount === undefined) return `${currency.symbol}0.00`;
  
  const numAmount = parseFloat(amount);
  if (isNaN(numAmount)) return `${currency.symbol}0.00`;
  
  // Special formatting for different currencies
  switch (currency.code) {
    case 'JPY':
    case 'KRW':
    case 'VND':
      return `${currency.symbol}${Math.round(numAmount).toLocaleString()}`;
    case 'INR':
      return `${currency.symbol}${numAmount.toFixed(2).replace(/\B(?=(\d{3})+(?!\d))/g, ',')}`;
    default:
      return `${currency.symbol}${numAmount.toFixed(2).replace(/\B(?=(\d{3})+(?!\d))/g, ',')}`;
  }
};

// Get currency symbol by code
export const getCurrencySymbol = (currencyCode) => {
  const currencyMap = {
    'USD': '$',
    'EUR': '€',
    'GBP': '£',
    'INR': '₹',
    'JPY': '¥',
    'CNY': '¥',
    'CAD': 'C$',
    'AUD': 'A$',
    'CHF': 'CHF',
    'SEK': 'kr',
    'NOK': 'kr',
    'DKK': 'kr',
    'PLN': 'zł',
    'CZK': 'Kč',
    'HUF': 'Ft',
    'BGN': 'лв',
    'RON': 'lei',
    'KRW': '₩',
    'HKD': 'HK$',
    'SGD': 'S$',
    'TWD': 'NT$',
    'THB': '฿',
    'MYR': 'RM',
    'IDR': 'Rp',
    'PHP': '₱',
    'VND': '₫',
    'BRL': 'R$',
    'MXN': '$',
    'ARS': '$',
    'CLP': '$',
    'COP': '$',
    'PEN': 'S/',
    'UYU': '$',
    'PYG': '₲',
    'BOB': 'Bs',
    'VES': 'Bs',
    'GYD': 'G$',
    'SRD': '$',
    'ZAR': 'R',
    'NGN': '₦',
    'KES': 'KSh',
    'GHS': '₵',
    'UGX': 'USh',
    'TZS': 'TSh',
    'ETB': 'Br',
    'MAD': 'د.م.',
    'EGP': 'E£',
    'DZD': 'د.ج',
    'TND': 'د.ت',
    'LYD': 'ل.د',
    'SDG': 'ج.س.',
    'SAR': 'ر.س',
    'AED': 'د.إ',
    'QAR': 'ر.ق',
    'KWD': 'د.ك',
    'BHD': 'د.ب',
    'OMR': 'ر.ع.',
    'JOD': 'د.ا',
    'LBP': 'ل.ل',
    'SYP': 'ل.س',
    'IQD': 'ع.د',
    'IRR': '﷼',
    'AFN': '؋',
    'PKR': '₨',
    'BDT': '৳',
    'LKR': 'Rs',
    'NPR': '₨',
    'BTN': 'Nu.',
    'MVR': 'MVR',
    'MMK': 'K',
    'KHR': '៛',
    'LAK': '₭',
    'MNT': '₮',
    'KZT': '₸',
    'UZS': 'so\'m',
    'KGS': 'с',
    'TJS': 'ЅМ',
    'TMT': 'T',
    'AZN': '₼',
    'GEL': '₾',
    'AMD': '֏',
    'UAH': '₴',
    'BYN': 'Br',
    'MDL': 'L',
    'RUB': '₽',
    'NZD': 'NZ$',
    'FJD': 'FJ$',
    'PGK': 'K',
    'SBD': 'SI$',
    'VUV': 'VT',
    'XPF': '₣',
    'WST': 'T',
    'TOP': 'T$',
    'BMD': '$',
    'KYD': '$',
    'XCD': '$',
    'BBD': '$',
    'TTD': '$',
    'JMD': '$',
    'HTG': 'G',
    'DOP': '$',
    'CUP': '$',
    'BSD': '$',
    'BZD': '$',
    'HNL': 'L',
    'NIO': 'C$',
    'CRC': '₡',
    'GTQ': 'Q',
    'ILS': '₪',
    'YER': '﷼',
    'SOS': 'Sh',
    'DJF': 'Fdj',
    'ERN': 'Nfk',
    'KMF': 'CF',
    'MGA': 'Ar',
    'MUR': '₨',
    'SCR': '₨',
    'SHP': '£',
    'FKP': '£',
    'GIP': '£',
    'ISK': 'kr',
    'GIP': '£',
    'BMD': '$',
    'KYD': '$',
    'XCD': '$',
    'BBD': '$',
    'TTD': '$',
    'JMD': '$',
    'HTG': 'G',
    'DOP': '$',
    'CUP': '$',
    'BSD': '$',
    'BZD': '$',
    'HNL': 'L',
    'NIO': 'C$',
    'CRC': '₡',
    'GTQ': 'Q'
  };
  
  return currencyMap[currencyCode] || '$';
};

// Get currency name by code
export const getCurrencyName = (currencyCode) => {
  const currencyMap = {
    'USD': 'US Dollar',
    'EUR': 'Euro',
    'GBP': 'British Pound',
    'INR': 'Indian Rupee',
    'JPY': 'Japanese Yen',
    'CNY': 'Chinese Yuan',
    'CAD': 'Canadian Dollar',
    'AUD': 'Australian Dollar',
    'CHF': 'Swiss Franc',
    'SEK': 'Swedish Krona',
    'NOK': 'Norwegian Krone',
    'DKK': 'Danish Krone',
    'PLN': 'Polish Złoty',
    'CZK': 'Czech Koruna',
    'HUF': 'Hungarian Forint',
    'BGN': 'Bulgarian Lev',
    'RON': 'Romanian Leu',
    'KRW': 'South Korean Won',
    'HKD': 'Hong Kong Dollar',
    'SGD': 'Singapore Dollar',
    'TWD': 'New Taiwan Dollar',
    'THB': 'Thai Baht',
    'MYR': 'Malaysian Ringgit',
    'IDR': 'Indonesian Rupiah',
    'PHP': 'Philippine Peso',
    'VND': 'Vietnamese Dong',
    'BRL': 'Brazilian Real',
    'MXN': 'Mexican Peso',
    'ARS': 'Argentine Peso',
    'CLP': 'Chilean Peso',
    'COP': 'Colombian Peso',
    'PEN': 'Peruvian Sol',
    'UYU': 'Uruguayan Peso',
    'PYG': 'Paraguayan Guaraní',
    'BOB': 'Bolivian Boliviano',
    'VES': 'Venezuelan Bolívar',
    'GYD': 'Guyanese Dollar',
    'SRD': 'Surinamese Dollar',
    'ZAR': 'South African Rand',
    'NGN': 'Nigerian Naira',
    'KES': 'Kenyan Shilling',
    'GHS': 'Ghanaian Cedi',
    'UGX': 'Ugandan Shilling',
    'TZS': 'Tanzanian Shilling',
    'ETB': 'Ethiopian Birr',
    'MAD': 'Moroccan Dirham',
    'EGP': 'Egyptian Pound',
    'DZD': 'Algerian Dinar',
    'TND': 'Tunisian Dinar',
    'LYD': 'Libyan Dinar',
    'SDG': 'Sudanese Pound',
    'SAR': 'Saudi Riyal',
    'AED': 'UAE Dirham',
    'QAR': 'Qatari Riyal',
    'KWD': 'Kuwaiti Dinar',
    'BHD': 'Bahraini Dinar',
    'OMR': 'Omani Rial',
    'JOD': 'Jordanian Dinar',
    'LBP': 'Lebanese Pound',
    'SYP': 'Syrian Pound',
    'IQD': 'Iraqi Dinar',
    'IRR': 'Iranian Rial',
    'AFN': 'Afghan Afghani',
    'PKR': 'Pakistani Rupee',
    'BDT': 'Bangladeshi Taka',
    'LKR': 'Sri Lankan Rupee',
    'NPR': 'Nepalese Rupee',
    'BTN': 'Bhutanese Ngultrum',
    'MVR': 'Maldivian Rufiyaa',
    'MMK': 'Myanmar Kyat',
    'KHR': 'Cambodian Riel',
    'LAK': 'Lao Kip',
    'MNT': 'Mongolian Tögrög',
    'KZT': 'Kazakhstani Tenge',
    'UZS': 'Uzbekistani Som',
    'KGS': 'Kyrgyzstani Som',
    'TJS': 'Tajikistani Somoni',
    'TMT': 'Turkmenistan Manat',
    'AZN': 'Azerbaijani Manat',
    'GEL': 'Georgian Lari',
    'AMD': 'Armenian Dram',
    'UAH': 'Ukrainian Hryvnia',
    'BYN': 'Belarusian Ruble',
    'MDL': 'Moldovan Leu',
    'RUB': 'Russian Ruble',
    'NZD': 'New Zealand Dollar',
    'FJD': 'Fijian Dollar',
    'PGK': 'Papua New Guinean Kina',
    'SBD': 'Solomon Islands Dollar',
    'VUV': 'Vanuatu Vatu',
    'XPF': 'CFP Franc',
    'WST': 'Samoan Tālā',
    'TOP': 'Tongan Paʻanga',
    'BMD': 'Bermudian Dollar',
    'KYD': 'Cayman Islands Dollar',
    'XCD': 'East Caribbean Dollar',
    'BBD': 'Barbadian Dollar',
    'TTD': 'Trinidad and Tobago Dollar',
    'JMD': 'Jamaican Dollar',
    'HTG': 'Haitian Gourde',
    'DOP': 'Dominican Peso',
    'CUP': 'Cuban Peso',
    'BSD': 'Bahamian Dollar',
    'BZD': 'Belize Dollar',
    'HNL': 'Honduran Lempira',
    'NIO': 'Nicaraguan Córdoba',
    'CRC': 'Costa Rican Colón',
    'GTQ': 'Guatemalan Quetzal',
    'ILS': 'Israeli Shekel',
    'YER': 'Yemeni Rial',
    'SOS': 'Somali Shilling',
    'DJF': 'Djiboutian Franc',
    'ERN': 'Eritrean Nakfa',
    'KMF': 'Comorian Franc',
    'MGA': 'Malagasy Ariary',
    'MUR': 'Mauritian Rupee',
    'SCR': 'Seychellois Rupee',
    'SHP': 'Saint Helena Pound',
    'FKP': 'Falkland Islands Pound',
    'GIP': 'Gibraltar Pound',
    'ISK': 'Icelandic Króna'
  };
  
  return currencyMap[currencyCode] || 'Unknown Currency';
};

// Convert amount between currencies (basic conversion - in production, use real exchange rates)
export const convertCurrency = (amount, fromCurrency, toCurrency) => {
  // This is a simplified conversion - in production, you'd use real exchange rates
  // For now, we'll use some basic conversion rates
  const conversionRates = {
    'USD': 1,
    'EUR': 0.85,
    'GBP': 0.73,
    'INR': 74.5,
    'JPY': 110.5,
    'CNY': 6.45,
    'CAD': 1.25,
    'AUD': 1.35,
    'CHF': 0.92,
    'SEK': 8.65,
    'NOK': 8.85,
    'DKK': 6.25,
    'PLN': 3.85,
    'CZK': 21.5,
    'HUF': 305.5,
    'BGN': 1.65,
    'RON': 4.15,
    'KRW': 1185.5,
    'HKD': 7.75,
    'SGD': 1.35,
    'TWD': 27.85,
    'THB': 32.5,
    'MYR': 4.15,
    'IDR': 14250,
    'PHP': 50.5,
    'VND': 23000,
    'BRL': 5.25,
    'MXN': 20.15,
    'ARS': 95.5,
    'CLP': 750,
    'COP': 3750,
    'PEN': 4.05,
    'UYU': 42.5,
    'PYG': 6850,
    'BOB': 6.85,
    'VES': 4.5,
    'GYD': 208.5,
    'SRD': 21.5,
    'ZAR': 14.85,
    'NGN': 410.5,
    'KES': 108.5,
    'GHS': 5.95,
    'UGX': 3550,
    'TZS': 2300,
    'ETB': 45.5,
    'MAD': 8.95,
    'EGP': 15.65,
    'DZD': 135.5,
    'TND': 2.85,
    'LYD': 4.55,
    'SDG': 55.5,
    'SAR': 3.75,
    'AED': 3.67,
    'QAR': 3.64,
    'KWD': 0.30,
    'BHD': 0.38,
    'OMR': 0.38,
    'JOD': 0.71,
    'LBP': 1500,
    'SYP': 1250,
    'IQD': 1460,
    'IRR': 42000,
    'AFN': 85.5,
    'PKR': 155.5,
    'BDT': 85.5,
    'LKR': 198.5,
    'NPR': 118.5,
    'BTN': 74.5,
    'MVR': 15.45,
    'MMK': 1650,
    'KHR': 4050,
    'LAK': 9500,
    'MNT': 2850,
    'KZT': 425,
    'UZS': 10500,
    'KGS': 84.5,
    'TJS': 11.35,
    'TMT': 3.5,
    'AZN': 1.7,
    'GEL': 3.15,
    'AMD': 485,
    'UAH': 27.5,
    'BYN': 2.55,
    'MDL': 17.85,
    'RUB': 75.5,
    'NZD': 1.45,
    'FJD': 2.05,
    'PGK': 3.55,
    'SBD': 8.05,
    'VUV': 115,
    'XPF': 105,
    'WST': 2.55,
    'TOP': 2.25,
    'BMD': 1,
    'KYD': 0.83,
    'XCD': 0.37,
    'BBD': 2,
    'TTD': 6.75,
    'JMD': 154.5,
    'HTG': 95.5,
    'DOP': 58.5,
    'CUP': 25,
    'BSD': 1,
    'BZD': 2,
    'HNL': 24.5,
    'NIO': 35.5,
    'CRC': 625,
    'GTQ': 7.75,
    'ILS': 3.25,
    'YER': 250,
    'SOS': 580,
    'DJF': 177.5,
    'ERN': 15.5,
    'KMF': 435,
    'MGA': 3950,
    'MUR': 40.5,
    'SCR': 20.5,
    'SHP': 0.73,
    'FKP': 0.73,
    'GIP': 0.73,
    'ISK': 125
  };
  
  const fromRate = conversionRates[fromCurrency] || 1;
  const toRate = conversionRates[toCurrency] || 1;
  
  return (amount / fromRate) * toRate;
}; 